package auth

import (
	"context"
	"errors"
	"fmt"
	"time"

	"streaming-backend/pkg/jwt"

	"golang.org/x/crypto/bcrypt"
)

// =============================================================================
// SERVICE LAYER (Business Logic)
// =============================================================================
// The Service contains the core business rules. It uses the Repository for data
// access and the JWT package for token generation. It knows nothing about HTTP.

type Service struct {
	repo      *Repository
	jwtSecret string
	jwtTTL    time.Duration
}

// NewService creates a new authentication service.
func NewService(repo *Repository, jwtSecret string, jwtTTL time.Duration) *Service {
	return &Service{
		repo:      repo,
		jwtSecret: jwtSecret,
		jwtTTL:    jwtTTL,
	}
}

var (
	ErrEmailExists      = errors.New("email is already registered")
	ErrUsernameExists   = errors.New("username is already taken")
	ErrInvalidCreds     = errors.New("invalid email or password")
	ErrValidationFailed = errors.New("validation failed")
)

// Register handles creating a new user account.
// 1. Validates input
// 2. Checks if email/username already exists
// 3. Hashes the password
// 4. Saves to database
// 5. Generates JWT
func (s *Service) Register(ctx context.Context, req RegisterRequest) (*AuthResponse, error) {
	// ─── Step 1: Basic Validation ─────────────────────────────────────────
	if req.Email == "" || len(req.Password) < 8 || req.Username == "" {
		return nil, fmt.Errorf("%w: missing required fields or password too short", ErrValidationFailed)
	}

	// ─── Step 2: Check for existing User ─────────────────────────────────
	emailExists, err := s.repo.EmailExists(ctx, req.Email)
	if err != nil {
		return nil, fmt.Errorf("registration failed during email check: %w", err)
	}
	if emailExists {
		return nil, ErrEmailExists
	}

	usernameExists, err := s.repo.UsernameExists(ctx, req.Username)
	if err != nil {
		return nil, fmt.Errorf("registration failed during username check: %w", err)
	}
	if usernameExists {
		return nil, ErrUsernameExists
	}

	// ─── Step 3: Hash Password ───────────────────────────────────────────
	// bcrypt.DefaultCost is 10. It makes brute-force attacks difficult.
	hashedPassword, err := bcrypt.GenerateFromPassword([]byte(req.Password), bcrypt.DefaultCost)
	if err != nil {
		return nil, fmt.Errorf("failed to hash password: %w", err)
	}

	// ─── Step 4: Save to Database  ────────────────────────────────────────
	newUser := &User{
		Email:        req.Email,
		Username:     req.Username,
		PasswordHash: string(hashedPassword),
		// Role, ID, and timestamps are handled by MySQL defaults
	}

	// Wait! We need the UUID generated by MySQL. Since MySQL UUID() executes on INSERT,
	// our `newUser` struct won't have the ID immediately. So we'll fetch the user back.
	if err := s.repo.CreateUser(ctx, newUser); err != nil {
		return nil, fmt.Errorf("failed to save user: %w", err)
	}
    
    // Fetch the full user from DB to get the generated ID and Role
    createdUser, err := s.repo.GetByEmail(ctx, req.Email)
    if err != nil {
        return nil, fmt.Errorf("failed to retrieve newly created user: %w", err)
    }

	// ─── Step 5: Generate JWT Token ───────────────────────────────────────
	token, err := jwt.GenerateToken(createdUser.ID, createdUser.Role, s.jwtSecret, s.jwtTTL)
	if err != nil {
		return nil, fmt.Errorf("failed to generate token: %w", err)
	}

	// ─── Step 6: Return Response ──────────────────────────────────────────
	return &AuthResponse{
		Token: token,
		User: UserInfo{
			ID:       createdUser.ID,
			Email:    createdUser.Email,
			Username: createdUser.Username,
			Role:     createdUser.Role,
		},
	}, nil
}

// Login authenticates an existing user.
// 1. Finds user by email
// 2. Compares hash with provided password
// 3. Generates JWT
func (s *Service) Login(ctx context.Context, req LoginRequest) (*AuthResponse, error) {
	// ─── Step 1: Basic Validation ─────────────────────────────────────────
	if req.Email == "" || req.Password == "" {
		return nil, fmt.Errorf("%w: missing email or password", ErrValidationFailed)
	}

	// ─── Step 2: Fetch User ───────────────────────────────────────────────
	user, err := s.repo.GetByEmail(ctx, req.Email)
	if err != nil {
		// Log the actual error internally, but always return generic ErrInvalidCreds
		// to prevent attackers from discovering which emails are registered.
		return nil, ErrInvalidCreds
	}

	// ─── Step 3: Verify Password ──────────────────────────────────────────
	err = bcrypt.CompareHashAndPassword([]byte(user.PasswordHash), []byte(req.Password))
	if err != nil {
		return nil, ErrInvalidCreds
	}

	// ─── Step 4: Generate JWT Token ───────────────────────────────────────
	token, err := jwt.GenerateToken(user.ID, user.Role, s.jwtSecret, s.jwtTTL)
	if err != nil {
		return nil, fmt.Errorf("failed to generate token: %w", err)
	}

	// ─── Step 5: Return Response ──────────────────────────────────────────
	return &AuthResponse{
		Token: token,
		User: UserInfo{
			ID:       user.ID,
			Email:    user.Email,
			Username: user.Username,
			Role:     user.Role,
		},
	}, nil
}
